### PR TITLE
ordinal of number over 100

### PR DESCRIPTION
**Pull request by AndersDJohnson**
Fixes ordinal function on numbers over 100.
Added a failing test case, then the bug fix.

### CODE REVIEW

**Comment by taijinlee** [comment]
Thanks! Good fix. I added a var and and semicolon on the tens line to keep it "proper". Hi to MN too =P though I don't think I really know anybody there that you would at this point ...

**Comment by AndersDJohnson** [comment]
*doh* var and semicolon - I have been writing CoffeeScript all day...

**Comment by taijinlee** [comment]
no worries. I prefer vanilla JS to coffescript personally. Have you been using humanize?

**Comment by AndersDJohnson** [comment]
I can dig vanilla JS too.
Just found humanize today; only used ordinal so far.

**Pull request merged**
