### PR TITLE
Refactored filesize to invoke humanize.intword.

### PR DESCRIPTION
**Pull request by michaek**
This defines a general-purpose function for formatting abbreviated humanized numbers, refactoring filesize() to call humanize.intword(). Passing tests included.

### CODE REVIEW

**Comment by taijinlee** [comment]
Hey, this is great -- I've seen at least one fork that needed to change the Mb -> MB kind of problem

A couple of small things I would change:

For intword, instead of setting defaults for `decimals`, `decPoints`, `thousandsSep` (I think those are the only culprits...), let's let `numberFormat` handle the defaults. We should just be able to pass it through instead of having more defaults logic

In intword, I don't think you need to initialize `var humanized = number` since it's set later, never operated on before that.

In filesize, instead of returning `'0 bytes'` when `filesize <= 0`, let's just set `filesize` to 0 and let `intword` handle the string generation

And lastly, it would be nice if `filesize` and `intword` had the same defaults for `suffixSep`. I think it'd be ok to say `suffixSep` defaults to `' '`. If we chose this path, I believe we can't say `suffixSep = suffixSep || ' '` because if you set it to `''`, it'll evaluate to false. Instead, you'll have to do a `=== undefined`

Thanks!

**Comment by michaek** [comment]
My changes were intended to modify the underlying code as little as possible.

The defaults for `decimals`, `decPoints`, `thousandsSep` were already in the filesize function. If you want further refactoring to DRY the existing code, I'd suggest that wait for another pull request.

Initializing `humanized = number` was left over from before I improved the for loop. It's redundant, and can be removed.

An early return of `'0 bytes'` was the previous behavior of the filesize method. If you'd like to change that, that's fine, but I don't think it needs to be in this pull request.

Yes, that's why the default is not ' '. If you're set on the default being the same, I can change that, but I think the defaults for intword support the proper output: '11K' rather than '11 K' - the space character will cause the output to look 'wrong' by default.

**Comment by taijinlee** [comment]
good points. I'll clean up the issues I have now later

Thanks!

**Comment by michaek** [comment]
Awesome. Thanks!

**Pull request merged**
